services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j_db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j/data:/data

  ollama:
    image: ollama/ollama
    container_name: ollama_local
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/models:/root/.ollama

  streamlit-app:
    build: .
    container_name: fraud_agent_ui
    ports:
      - "8501:8501"
    depends_on:
      - neo4j
      - ollama
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - OLLAMA_HOST=http://ollama:11434
